# Generated by Django 4.1.5 on 2023-02-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='month_of_expense',
            field=models.CharField(default=False, max_length=120),
        ),
        migrations.AddField(
            model_name='expense',
            name='year_of_expense',
            field=models.CharField(default=False, max_length=120),
        ),
    ]
