# Generated by Django 4.1.5 on 2023-02-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_expense_month_of_expense_expense_year_of_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
    ]
